# Generated by Django 4.0.6 on 2022-08-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Student', models.CharField(max_length=50)),
                ('Mobile_Number', models.IntegerField()),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=40)),
            ],
        ),
    ]
